<a href="https://colab.research.google.com/github/mkssmanish/python-programs/blob/master/Numpy_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
### when python lists are already there ###
### Why do we need NumPy ? ###


# The answer to it is we cannot perform operations 
#... on all the elements of two list directly. For example, 
#... we cannot multiply two lists directly we will have to do it element-wise. 
#... This is where the role of NumPy comes into play.

In [1]:
# Python program to demonstrate a need of NumPy
 
list1 = [1, 2, 3, 4 ,5, 6]
list2 = [10, 9, 8, 7, 6, 5]
 
# Multiplying both lists directly would give an error.
print(list1*list2)

TypeError: ignored

In [3]:
import numpy as np
list1 = np.array(list1)
list2 = np.array(list2)

print(list1 * list2 )

[10 18 24 28 30 30]


In [0]:
# Create a sequence of integers from
# 10 to 0  with a step of -3
a = np.arange(10,0 , -3)
print(a)

In [0]:
print("a = ", a)
new_arr = a[np.array([2,0,1 ])]
new_arr

In [0]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Index values can be negative.
arr = x[np.array([0,3,-3])]
print("\n Elements are : \n",arr)

In [0]:
#########  Types of Indexing ###########

In [36]:
# Python program for basic slicing.
import numpy as np
 
# Arrange elements from 0 to 19
a = np.arange(20)
print("\n Array is:\n ",a)

negative_index = np.arange(-20,0,1)
print("\n negative index  is:\n ",negative_index)
 
# a[start:stop:step]

print("\n -8 = 12th index --> a[-8:17:1]  = ",a[-8:17:1]) 



print("\n\n\n  a[8:-17:-1] will give index 8,7,6,5,4  bcz -17 mean 3rd index --> 8  loop(-1) till 3rd index   ",a[8:-17:-1]) 



print("\n\n\n a[8:12:-1] will give empty array bcz 8th index increment with (-1) cant lead u to 12th index  = ",a[8:12:-1]) 


print("\n\n\n -8 mean 12th index , -12 mean +8th index  a[-8:-12:-1] will give array with index -8 -9 -10 -11   = ",a[-8:-12:-1]) 

 
# The : operator means all elements till the end.
print("\n\n\n a[10:]  = ",a[10:])


 Array is:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 negative index  is:
  [-20 -19 -18 -17 -16 -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3
  -2  -1]

 -8 = 12th index --> a[-8:17:1]  =  [12 13 14 15 16]



  a[8:-17:-1] will give index 8,7,6,5,4  bcz -17 mean 3rd index --> 8  loop(-1) till 3rd index    [8 7 6 5 4]



 a[8:12:-1] will give empty array bcz 8th index increment with (-1) cant lead u to 12th index  =  []



 -8 mean 12th index , -12 mean +8th index  a[-8:-12:-1] will give array with index -8 -9 -10 -11   =  [12 11 10  9]



 a[10:]  =  [10 11 12 13 14 15 16 17 18 19]


In [55]:
# Python program for basic slicing 
# and indexing
import numpy as np
 
# A 3-Dimensional array
a = np.array([[0, 1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10, 11],
              [12, 13, 14, 15, 16, 17],
              [18, 19, 20, 21, 22, 23],
              [24, 25, 26, 27, 28, 29],
              [30, 31, 32, 33, 34, 35]])
print("\n Array is:\n ",a)
 
# slicing and indexing
print("\n a[0, 3:5]  = ",a[0, 3:5]) 
 
print("\n a[4:, 4:]  = ",a[4:, 4:]) 
 
print("\n a[:, 2]  = ",a[:, 2]) 
 
print("\n a[2::2, ::2]  = ",a[2::2, ::2]) 
print(" a[...,1]) #Equivalent to a[: ,: ,1 ]  ")
print(a[...,5]) #Equivalent to a[: ,: ,1 ]
print(a[:,::5])



 Array is:
  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

 a[0, 3:5]  =  [3 4]

 a[4:, 4:]  =  [[28 29]
 [34 35]]

 a[:, 2]  =  [ 2  8 14 20 26 32]

 a[2::2, ::2]  =  [[12 14 16]
 [24 26 28]]
 a[...,1]) #Equivalent to a[: ,: ,1 ]  
[ 5 11 17 23 29 35]
[[ 0  5]
 [ 6 11]
 [12 17]
 [18 23]
 [24 29]
 [30 35]]
